<?php
    /**
     * @file 404.phtml
     * @author kevin leonel sangoluisa luge
     * @version 1.1
     * @breif pagina de error cuando no encuentra la pagina web en el servidor
     * este tipo de codigos se divide en tres partes, 
     * el primer digito es la clase del codigo, 
     * el segundo seria la subcategoria dentro del primer digito que este caso seria el 4
     * el terver digito es un codigo especifico que estan definidos del 0 al 9
     */
?>
<p>ERROR 404 - La página que busca no existe.</p>